#!/bin/bash
# Generated by RemoteHPC
# job-name qe_eos_pbe_d0.0
source /opt/intel/oneapi/2024.1/oneapi-vars.sh
mpirun -np 4 /home/guoyuan/src/qef-qe/build_intel/bin/pw.x -nk 4 < vcrelax.in > vcrelax.out
# mpirun -np 4 /home/guoyuan/src/qef-qe/build_intel/bin/pw.x -nk 4 < scf.in > scf.out
# mpirun -np 4 /home/guoyuan/src/qef-qe/build_intel/bin/pw.x -nk 4 < bands.in > bands.out
# mpirun -np 4 /home/guoyuan/src/qef-qe/build_intel/bin/pw.x -nk 4 < nscf.in > nscf.out
# mpirun -np 4 /home/guoyuan/src/qef-qe/build_intel/bin/projwfc.x < projwfc.in > projwfc.out
